version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with "chore(deps): "
      prefix: "chore(deps)"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with "chore(deps): "
      prefix: "chore(deps)"
