repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=1024']
          - id: check-merge-conflict
          - id: detect-aws-credentials
            args:
                - '--allow-missing-credentials'
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
            name: Fix UTF-8 byte order marker
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]

    - repo: https://github.com/sirosen/fix-smartquotes
      rev: 0.2.0
      hooks:
          - id: fix-smartquotes

    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.4.0
      hooks:
          - id: go-fmt
            name: Golang Formatting

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.1
      hooks:
          - id: ruff
            name: Ruff Linting
            args: [--fix]
            types_or: [python, pyi, jupyter]
            pass_filenames: false
          - id: ruff-format
            name: Ruff Formatting
            types_or: [python, pyi, jupyter]
            pass_filenames: false

    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.14.0
      hooks:
          - id: check-jsonschema
            name: 'Validate Zarf Configs Against Schema'
            files: 'zarf.yaml'
            types: [yaml]
            args: ['--schemafile', 'zarf.schema.json']
