package:
  create:
    set:
      image_repository: "ghcr.io/justinthelaw/repository-template/example"
      # x-release-please-start-version
      image_version: 0.7.2
      # x-release-please-end
      name: example
    max_package_size: "1000000000"
