name: Check Licenses

on:
  pull_request:
    branches: [ main ]

jobs:
  check-licenses:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version-file: 'pyproject.toml' # Read python version from a file pyproject.toml

    - name: Install pip-licenses
      run: pip install pip-licenses

    - name: Check Python licenses
      run: |
        pip-licenses --from=mixed --with-license-file | grep -E 'MIT|Apache Software License' > python-licenses.txt || exit 1

    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: Install license-checker
      run: npm install -g license-checker

    - name: Check NPM licenses
      run: |
        license-checker --summary | grep -E 'MIT|Apache-2.0' > npm-licenses.txt || exit 1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install go-licenses
      run: go get github.com/google/go-licenses

    - name: Check Go licenses
      run: |
        go-licenses check ./... | grep -E 'MIT|Apache-2.0' > go-licenses.txt || exit 1

    - name: Check model licenses
      run: |
        cat licenses.json | grep -E 'MIT|Apache-2.0' > model-licenses.txt || exit 1
