name: Lint Manifests

on:
  push:
    branches:
      - '!main'
  pull_request:
      branches: [main]

concurrency:
  group: manifest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@6c2b7200d597e38a3f2cd901b50046c800fc144b # v4.0.0
        with:
          exec: helm lint ./chart

  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: lint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile
