name: Node Lint and Format

on:
    pull_request:
        branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Formatting
        run: npm run format
