name: Playwright Tests

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.svelte'

concurrency:
  group: playwright-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1


      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Playwright tests
        uses: docker://mcr.microsoft.com/playwright:v1.41.1-jammy
        with:
          args: env HOME=/root npx playwright test

      - name: Upload Results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 15
