name: Publish Artifacts

on:
  push:
    tags:
      - "v*.*.*"
      - "dev"

jobs:
  zarf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Login to GHCR
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build API Image
      run: make docker-build docker-push VERSION=$GITHUB_REF_NAME

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@f95763914e20e493bb5d45d63e30e17138f981d6 # v1.0.0

    - name: Build Zarf Package
      run: make zarf-create

    - name: Publish Zarf Package
      run: make zarf-publish
