name: Python Test

on: [pull_request, push]

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

          - name: Set up Python 3.11.6
            uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
            with:
              python-version: 3.11.6

          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              make requirements-dev

          - name: Run Tests
            run: |
              make test
